export const cartToggleActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
};
